### ISSUE TITLE
pifpaf psutil.AccessDenied

### ISSUE THREAD

**Issue by maximumG** [jd/pifpaf#113]
Hello,

I'm trying to use pifpaf in my tox testing automation suite but always fall under a weird issue.

I launch the following command before the tests as a standard user (non root)

```bash
pifpaf run mysql $SHELL
```

After the test I just use the exit command to log out from the created shell. Under normal circumstances, the mysqld process should be killed, rather it always raise the following exceptions

```python
CRITICAL [root] Traceback (most recent call last):
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/psutil/__init__.py", line 1169, in _send_signal
    os.kill(self.pid, sig)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gerges/PycharmProjects/freeradius-api/venv/bin/pifpaf", line 11, in <module>
    sys.exit(run_main())
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/pifpaf/__main__.py", line 269, in run_main
    return main.main(standalone_mode=False)
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/pifpaf/__main__.py", line 140, in _run_cb
    return self._run(name, plugin, ctx, *args, **kwargs)
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/pifpaf/__main__.py", line 188, in _run
    return c.wait()
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/fixtures/fixture.py", line 157, in __exit__
    self._cleanups()
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/fixtures/callmany.py", line 89, in __call__
    reraise(error[0], error[1], error[2])
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/testtools/_compat3x.py", line 16, in reraise
    raise exc_obj.with_traceback(exc_tb)
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/fixtures/callmany.py", line 83, in __call__
    cleanup(*args, **kwargs)
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/pifpaf/drivers/__init__.py", line 129, in _kill
    parent.terminate()
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/psutil/__init__.py", line 284, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/psutil/__init__.py", line 1233, in terminate
    self._send_signal(signal.SIGTERM)
  File "/home/gerges/PycharmProjects/freeradius-api/venv/lib/python3.6/site-packages/psutil/__init__.py", line 1180, in _send_signal
    raise AccessDenied(self.pid, self._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=10326)
```
Even when trying to kill the process using root (kill -9), it takes quite some time and the mysqld process end up as Zombie status.

Do you have any clue on this issue ? Am i doing something wrong with pifpaf ?

**Comment by maximumG** [comment]
I just found the solution. From the Pycharm Terminal utility, pifpaf is not able to kill the mysql process (the errors above were coming from the Pycharm Terminal). 

However when using a standard linux terminal, the issue does not arise and everything is working as expected.
