### ISSUE TITLE
terminating PIFPAF_PID hangs forever in 3.1.4 (works in 3.1.1)

### ISSUE THREAD

**Issue by graingert** [jd/pifpaf#143]
here's a demo Dockerfile with a repro: https://github.com/graingert/pifpaf-hang/blob/default/demo.py#L39-L40

and here's a demo of me running it with pifpaf 3.1.1 terminating successfully and 3.1.4 hanging forever https://asciinema.org/a/388367 (I actually timeout after 10 seconds)

**Comment by jd** [comment]
Thanks for the report @graingert.
Can you take a look at #144 and tell me if it fixes the issue?

**Comment by graingert** [comment]
Is there something I should be doing to make sure etcd terminates cleanly?

**Comment by jd** [comment]
I don't think so, processes terminate differently depending on how they can be shutdown.

**Comment by graingert** [comment]
@jd I can't install the package with pip-tools

```
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    pifpaf from git+https://github.com/jd/pifpaf@532ea934c37a31653965bd734ce33ab62a016483#egg=pifpaf (from -r requirements-pifpaf-fix.txt (line 138))
```

**Comment by jd** [comment]
```
pip install 'git+https://github.com/jd/pifpaf@532ea934c37a31653965bd734ce33ab62a016483#egg=pifpaf'
```
works fine here

**Comment by graingert** [comment]
@jd here's my repro with that commit: https://github.com/graingert/pifpaf-hang/commit/cdb58832671834dc2e81cdd52c98ea8c706167ee

**Comment by jd** [comment]
What's the result of the repro?

**Comment by graingert** [comment]
@jd I get the "Can't verify hashes" error from before. I tried with the github archive URL:

```
      ERROR: Command errored out with exit status 1:
       command: /home/graingert/.virtualenvs/pip-compile39/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-t9m1z6h5/pifpaf/setup.py'"'"'; __file__='"'"'/tmp/pip-resolver-t9m1z6h5/pifpaf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ca58xtl1
           cwd: /tmp/pip-resolver-t9m1z6h5/pifpaf/
      Complete output (16 lines):
      ERROR:root:Error parsing
      Traceback (most recent call last):
        File "/tmp/pip-resolver-t9m1z6h5/pifpaf/.eggs/pbr-5.5.1-py3.9.egg/pbr/core.py", line 96, in pbr
          attrs = util.cfg_to_args(path, dist.script_args)
        File "/tmp/pip-resolver-t9m1z6h5/pifpaf/.eggs/pbr-5.5.1-py3.9.egg/pbr/util.py", line 271, in cfg_to_args
          pbr.hooks.setup_hook(config)
        File "/tmp/pip-resolver-t9m1z6h5/pifpaf/.eggs/pbr-5.5.1-py3.9.egg/pbr/hooks/__init__.py", line 25, in setup_hook
          metadata_config.run()
        File "/tmp/pip-resolver-t9m1z6h5/pifpaf/.eggs/pbr-5.5.1-py3.9.egg/pbr/hooks/base.py", line 27, in run
          self.hook()
        File "/tmp/pip-resolver-t9m1z6h5/pifpaf/.eggs/pbr-5.5.1-py3.9.egg/pbr/hooks/metadata.py", line 25, in hook
          self.config['version'] = packaging.get_version(
        File "/tmp/pip-resolver-t9m1z6h5/pifpaf/.eggs/pbr-5.5.1-py3.9.egg/pbr/packaging.py", line 874, in get_version
          raise Exception("Versioning for this project requires either an sdist"
      Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pifpaf was given, but was not able to be found.
      error in setup command: Error parsing /tmp/pip-resolver-t9m1z6h5/pifpaf/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pifpaf was given, but was not able to be found.
```

**Comment by jd** [comment]
Ha. Can you generate a tarball or something and embed it?

**Comment by graingert** [comment]
@jd installing without hash checking works for me: https://github.com/graingert/pifpaf-hang/commit/31a75c5dec9dafcf9c225357805278e0eeb0b1ba

```
Step 8/10 : RUN ~/.virtualenvs/pifpaf311/bin/python -m demo
 ---> Running in e14c71621ca1
port='2379'
Removing intermediate container e14c71621ca1
 ---> 58adefe291af
Step 9/10 : RUN ~/.virtualenvs/pifpaf-fix/bin/python -m demo
 ---> Running in 0466a8a4320d
port='2379'
Removing intermediate container 0466a8a4320d
 ---> de7a31e30d58
```

**Comment by jd** [comment]
Great, I'll merge it then.

**Comment by graingert** [comment]
@jd amazing thanks for the fix!
