### ISSUE TITLE
0.10.2 failing mysql tests with mariadb

### ISSUE THREAD

**Issue by felixonmars** [jd/pifpaf#15]
I am getting the following errors when running tests with mariadb 10.1.16. There is no issue when running the tests with percona 5.7.13_6, so it appears to be mariadb-specific.

```
running testr
running=${PYTHON:-python} -m subunit.run discover -t . pifpaf/tests --list
running=${PYTHON:-python} -m subunit.run discover -t . pifpaf/tests  --load-list /tmp/tmpb9pcfj3w
running=${PYTHON:-python} -m subunit.run discover -t . pifpaf/tests  --load-list /tmp/tmp0npul3x1
running=${PYTHON:-python} -m subunit.run discover -t . pifpaf/tests  --load-list /tmp/tmp62xofra3
running=${PYTHON:-python} -m subunit.run discover -t . pifpaf/tests  --load-list /tmp/tmpol696vun
======================================================================
FAIL: pifpaf.tests.test_drivers.TestDrivers.test_mysql
tags: worker-0
----------------------------------------------------------------------
traceback-1: {{{
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()
  File "/build/python-pifpaf/src/pifpaf/pifpaf/drivers/mysql.py", line 39, in _setUp
    "--datadir=" + datadir])
  File "/build/python-pifpaf/src/pifpaf/pifpaf/drivers/__init__.py", line 151, in _exec
    raise RuntimeError("Error while running command: %s" % command)
RuntimeError: Error while running command: ['mysql_install_db', '--no-defaults', '--tmpdir=/tmp/tmprguk41s_/tmp', '--datadir=/tmp/tmprguk41s_/data']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/fixtures/fixture.py", line 208, in setUp
    raise SetupError(details)
fixtures.fixture.SetupError: {}
}}}

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/fixtures/fixture.py", line 197, in setUp
    self._setUp()
  File "/build/python-pifpaf/src/pifpaf/pifpaf/drivers/mysql.py", line 39, in _setUp
    "--datadir=" + datadir])
  File "/build/python-pifpaf/src/pifpaf/pifpaf/drivers/__init__.py", line 151, in _exec
    raise RuntimeError("Error while running command: %s" % command)
RuntimeError: Error while running command: ['mysql_install_db', '--no-defaults', '--tmpdir=/tmp/tmprguk41s_/tmp', '--datadir=/tmp/tmprguk41s_/data']
Ran 25 tests in 3.332s
FAILED (id=0, failures=1, skips=14)
error: testr failed (1)
```

Running the command manually results in the following error message:
```
FATAL ERROR: Could not find ./bin/my_print_defaults

If you compiled from source, you need to either run 'make install' to
copy the software into the correct location ready for operation.
If you don't want to do a full install, you can use the --srcddir
option to only install the mysql database and privilege tables

If you are using a binary release, you must either be at the top
level of the extracted archive, or pass the --basedir option
pointing to that location.

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
```

Adding `--basedir=/usr` to command line fixes this.

**Comment by jd** [comment]
@felixonmars let me know if the fix work, and I'll release a new version!

**Comment by felixonmars** [comment]
It fails at the last part:

```
        self._exec(["mysql",
                    "--no-defaults",
                    "-S", self.socket,
                    "-e", "CREATE DATABASE test;"])
```

**Comment by jd** [comment]
@felixonmars adding --basedir=/usr fixes it also? or something else?

**Comment by felixonmars** [comment]
The error is:
```
ERROR 1007 (HY000) at line 1: Can't create database 'test'; database exists
```

I have tried to change all occurrences to 'test_pifpaf' and the tests successfully passed.

**Comment by felixonmars** [comment]
Quoting from https://mariadb.com/kb/en/mariadb/mysql_secure_installation/ :
> By default, MariaDB comes with a database named 'test' that anyone can access.

**Comment by jd** [comment]
I had to revert the fix, because in some cases the base dir is not /usr. I've tested MariaDB with Homebrew on Darwin, and this still works correctly.

**Comment by felixonmars** [comment]
That's really unfortunate :(
Would it be a good idea to just pick up some values from defaults?

**Comment by jd** [comment]
If you're able to have a patch that does that, for sure @felixonmars.
