### ISSUE TITLE
pip install pifpaf in ubuntu 16.04 with python 3 is broken

### ISSUE THREAD

**Issue by cristicalin** [jd/pifpaf#78]
**Steps to reproduce**

On an ubuntu 16.04 docker image:

```
python3 -m virtualenv -p python3 /tmp/venv
source /tmp/venv/bin/activate
pip install -U pip wheel devpi-client setuptools
pip install pifpaf
```

The install step will throw an ascii decode error:

```
(venv) root@84678a3049d7:/work# pip install pifpaf
Collecting pifpaf
  Using cached pifpaf-1.10.2.tar.gz
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-rl5qoc1q/pifpaf/.eggs/pbr-3.1.1-py3.5.egg
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/tmp/pip-build-rl5qoc1q/pifpaf/.eggs/pbr-3.1.1-py3.5.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/tmp/pip-build-rl5qoc1q/pifpaf/.eggs/pbr-3.1.1-py3.5.egg/pbr/util.py", line 249, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/tmp/pip-build-rl5qoc1q/pifpaf/.eggs/pbr-3.1.1-py3.5.egg/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/tmp/pip-build-rl5qoc1q/pifpaf/.eggs/pbr-3.1.1-py3.5.egg/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/tmp/pip-build-rl5qoc1q/pifpaf/.eggs/pbr-3.1.1-py3.5.egg/pbr/hooks/metadata.py", line 26, in hook
        self.config['name'], self.config.get('version', None))
      File "/tmp/pip-build-rl5qoc1q/pifpaf/.eggs/pbr-3.1.1-py3.5.egg/pbr/packaging.py", line 737, in get_version
        version = _get_version_from_pkg_metadata(package_name)
      File "/tmp/pip-build-rl5qoc1q/pifpaf/.eggs/pbr-3.1.1-py3.5.egg/pbr/packaging.py", line 705, in _get_version_from_pkg_metadata
        pkg_metadata = email.message_from_file(pkg_metadata_file)
      File "/usr/lib/python3.5/email/__init__.py", line 54, in message_from_file
        return Parser(*args, **kws).parse(fp)
      File "/usr/lib/python3.5/email/parser.py", line 54, in parse
        data = fp.read(8192)
      File "/tmp/venv/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3106: ordinal not in range(128)
    error in setup command: Error parsing /tmp/pip-build-rl5qoc1q/pifpaf/setup.cfg: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3106: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rl5qoc1q/pifpaf/
```

Is there anything I'm missing?
Here is the output of pip list in that venv:

```
(venv) root@84678a3049d7:/work# pip list --format=columns
Package        Version
-------------- -----------
certifi        2017.7.27.1
chardet        3.0.4
check-manifest 0.35
devpi-client   3.0.0
devpi-common   3.1.0
idna           2.6
pip            9.0.1
pkg-resources  0.0.0
pkginfo        1.4.1
pluggy         0.5.2
py             1.4.34
requests       2.18.4
setuptools     36.5.0
tox            2.8.2
urllib3        1.22
virtualenv     15.1.0
wheel          0.30.0
```

**Comment by jd** [comment]
I don't even see any Unicode thing in `setup.cfg` so I'm lost.

**Comment by cristicalin** [comment]
Ok, so problem is in README.rst as 'pbr' reads it and passes it to setuptools.
More specifically, it's this section (GitHub does not allow me to link to lines in README.rst):

```
template1=# \l
                              List of databases
   Name    │ Owner │ Encoding │   Collate   │    Ctype    │ Access privileges
───────────┼───────┼──────────┼─────────────┼─────────────┼───────────────────
 postgres  │ jd    │ UTF8     │ en_US.UTF-8 │ en_US.UTF-8 │
 template0 │ jd    │ UTF8     │ en_US.UTF-8 │ en_US.UTF-8 │ =c/jd            ↵
           │       │          │             │             │ jd=CTc/jd
 template1 │ jd    │ UTF8     │ en_US.UTF-8 │ en_US.UTF-8 │ =c/jd            ↵
           │       │          │             │             │ jd=CTc/jd
(3 rows)

template1=# \q
$
```

**Comment by jd** [comment]
Ha that makes more sense. I imagine your locale is not set to something UTC-8 compatible?

**Comment by cristicalin** [comment]
I don't have anything set for that environment so I guess it defaults to `C`.
