### ISSUE TITLE
Trouble installing and running pifpaf 1.12.0

### ISSUE THREAD

**Issue by sinemetu1** [jd/pifpaf#90]
Hello, It looks like pifpaf isn't installing its dependencies when I `python setup.py install` it.

```
🔥 🚬 🚬 🚬 😮  pifpaf $ git checkout tags/1.12.0
Note: checking out 'tags/1.12.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c067694... Wait logging thread and close the fd
🔥 🚬 🚬 🚬 😮  pifpaf $ virtualenv venv
Using base prefix '/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6'
New python executable in /Users/samuelgarrett/workspace/tmp/pifpaf/venv/bin/python3.6
Also creating executable in /Users/samuelgarrett/workspace/tmp/pifpaf/venv/bin/python
Installing setuptools, pip, wheel...done.
🔥 🚬 🚬 🚬 😮  pifpaf $ source venv/bin/activate
(venv) 🔥 🚬 🚬 🚬 😮  pifpaf $ python setup.py install
running install
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.0s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.0s)
running build
running build_py
running egg_info
writing pbr to pifpaf.egg-info/pbr.json
writing pifpaf.egg-info/PKG-INFO
writing dependency_links to pifpaf.egg-info/dependency_links.txt
writing entry points to pifpaf.egg-info/entry_points.txt
writing requirements to pifpaf.egg-info/requires.txt
writing top-level names to pifpaf.egg-info/top_level.txt
[pbr] Processing SOURCES.txt
[pbr] In git context, generating filelist from git
warning: no previously-included files found matching '.gitreview'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'pifpaf.egg-info/SOURCES.txt'
running install_lib
creating /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf
copying build/lib/pifpaf/__init__.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf
copying build/lib/pifpaf/__main__.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf
creating /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/__init__.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/aodh.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/ceph.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/consul.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/couchdb.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/elasticsearch.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/etcd.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/fakes3.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/gnocchi.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/influxdb.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/kafka.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/keystone.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/memcached.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/mongodb.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/mysql.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/postgresql.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/rabbitmq.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/redis.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/s3rver.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/swift.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
creating /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates
creating /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift
copying build/lib/pifpaf/drivers/templates/swift/account.conf -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift
copying build/lib/pifpaf/drivers/templates/swift/common.conf.inc -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift
copying build/lib/pifpaf/drivers/templates/swift/container-sync-realms.conf -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift
copying build/lib/pifpaf/drivers/templates/swift/container.conf -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift
copying build/lib/pifpaf/drivers/templates/swift/object.conf -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift
copying build/lib/pifpaf/drivers/templates/swift/proxy.conf -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift
copying build/lib/pifpaf/drivers/templates/swift/sitecustomize.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift
copying build/lib/pifpaf/drivers/templates/swift/swift.conf -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift
copying build/lib/pifpaf/drivers/vault.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
copying build/lib/pifpaf/drivers/zookeeper.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers
creating /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/tests
copying build/lib/pifpaf/tests/__init__.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/tests
copying build/lib/pifpaf/tests/test_cli.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/tests
copying build/lib/pifpaf/tests/test_drivers.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/tests
copying build/lib/pifpaf/tests/unkillable.py -> /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/tests
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/__init__.py to __init__.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/__main__.py to __main__.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/__init__.py to __init__.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/aodh.py to aodh.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/ceph.py to ceph.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/consul.py to consul.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/couchdb.py to couchdb.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/elasticsearch.py to elasticsearch.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/etcd.py to etcd.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/fakes3.py to fakes3.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/gnocchi.py to gnocchi.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/influxdb.py to influxdb.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/kafka.py to kafka.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/keystone.py to keystone.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/memcached.py to memcached.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/mongodb.py to mongodb.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/mysql.py to mysql.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/postgresql.py to postgresql.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/rabbitmq.py to rabbitmq.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/redis.py to redis.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/s3rver.py to s3rver.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/swift.py to swift.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/templates/swift/sitecustomize.py to sitecustomize.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/vault.py to vault.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/drivers/zookeeper.py to zookeeper.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/tests/__init__.py to __init__.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/tests/test_cli.py to test_cli.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/tests/test_drivers.py to test_drivers.cpython-36.pyc
byte-compiling /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/tests/unkillable.py to unkillable.cpython-36.pyc
running install_egg_info
Copying pifpaf.egg-info to /Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf-1.12.0-py3.6.egg-info
running install_scripts
Installing pifpaf script to /Users/samuelgarrett/workspace/tmp/pifpaf/venv/bin
(venv) 🔥 🚬 🚬 🚬 😮  pifpaf $ pifpaf
Traceback (most recent call last):
  File "/Users/samuelgarrett/workspace/tmp/pifpaf/venv/bin/pifpaf", line 6, in <module>
    from pifpaf.__main__ import main
  File "/Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/__main__.py", line 24, in <module>
    from cliff import app
ModuleNotFoundError: No module named 'cliff'
(venv) 🔥 🚬 🚬 🚬 😮  pifpaf $ pip install cliff
Collecting cliff
Collecting PyYAML>=3.10 (from cliff)
Collecting pbr!=2.1.0,>=2.0.0 (from cliff)
  Using cached pbr-3.1.1-py2.py3-none-any.whl
Collecting cmd2>=0.6.7 (from cliff)
Collecting six>=1.10.0 (from cliff)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pyparsing>=2.1.0 (from cliff)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting stevedore>=1.20.0 (from cliff)
  Using cached stevedore-1.28.0-py2.py3-none-any.whl
Collecting PrettyTable<0.8,>=0.7.1 (from cliff)
Collecting pyperclip (from cmd2>=0.6.7->cliff)
Installing collected packages: PyYAML, pbr, pyparsing, six, pyperclip, cmd2, stevedore, PrettyTable, cliff
Successfully installed PrettyTable-0.7.2 PyYAML-3.12 cliff-2.10.0 cmd2-0.7.9 pbr-3.1.1 pyparsing-2.2.0 pyperclip-1.6.0 six-1.11.0 stevedore-1.28.0
(venv) 🔥 🚬 🚬 🚬 😮  pifpaf $ pifpaf
Traceback (most recent call last):
  File "/Users/samuelgarrett/workspace/tmp/pifpaf/venv/bin/pifpaf", line 6, in <module>
    from pifpaf.__main__ import main
  File "/Users/samuelgarrett/workspace/tmp/pifpaf/venv/lib/python3.6/site-packages/pifpaf/__main__.py", line 29, in <module>
    import daiquiri
ModuleNotFoundError: No module named 'daiquiri'
(venv) 🔥 🚬 🚬 🚬 😮  pifpaf $ 
```

Any ideas?

Any help is appreciated. Thanks!

**Comment by sinemetu1** [comment]
Also, in my other projects where I have pifpaf declared as a test dependency like this in `tox.ini`:

```
[testenv]
deps =
    pytest
    coverage
    mock
    pifpaf
```

pifpaf installs fine but then when I try to run a command I get:

```
pifpaf: 'run mongodb -- pifpaf run postgresql -- python -m coverage run -m pytest tests' is not a pifpaf command. See 'pifpaf --help'.
Did you mean one of these?
  help
ERROR: InvocationError: '/Users/samuelgarrett/workspace/some-proj/.tox/py27/bin/pifpaf run mongodb -- pifpaf run postgresql -- python -m coverage run -m pytest tests'
```

I also tried installing with `pip install pifpaf` in a fresh virtualenv and I received the same output. It looks like the `run` command is gone. 🤔

**Comment by jd** [comment]
> pifpaf $ python setup.py install

Don't use setup.py, use pip.

Use `pip install .` in a fresh env.

**Comment by sinemetu1** [comment]
Looks like this PR https://github.com/jd/pifpaf/pull/91 and release https://github.com/jd/pifpaf/releases/tag/1.12.1 fix our issues with pifpaf not having a `run` command.

Thanks for your help!
